"""Run all retrieval profiles on the golden set and write an ablation table (item 22).

Requires a running API with fixtures already ingested. Does not invent metrics:
every number in the report comes from a live eval_retrieval pass.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

PROFILES = ["vector", "hybrid", "hybrid_rerank", "parent_child", "multi_query"]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-url", default="http://localhost:8000")
    parser.add_argument("--user", required=True)
    parser.add_argument("--password", required=True)
    parser.add_argument("--file", default="eval/golden_set.jsonl")
    parser.add_argument("--out-dir", default="eval/reports")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    summary_rows = []

    for profile in PROFILES:
        report_path = out_dir / f"{profile}.json"
        cmd = [
            sys.executable,
            "scripts/eval_retrieval.py",
            "--base-url",
            args.base_url,
            "--user",
            args.user,
            "--password",
            args.password,
            "--file",
            args.file,
            "--profile",
            profile,
            "--out",
            str(report_path),
        ]
        print(f"=== profile={profile} ===")
        result = subprocess.run(cmd, check=False)
        if result.returncode != 0 or not report_path.exists():
            print(f"[WARN] profile {profile} failed; skipping from summary")
            continue
        report = json.loads(report_path.read_text(encoding="utf-8"))
        summary_rows.append(
            {
                "profile": profile,
                "hit_rate_at_5": report["hit_rate_at_5"],
                "mrr": report["mrr"],
                "ndcg_at_5": report["ndcg_at_5"],
                "no_answer_false_positive_rate": report["no_answer_false_positive_rate"],
                "p95_retrieval_ms": report["p95_retrieval_ms"],
                "case_count": report["case_count"],
            }
        )

    summary_path = out_dir / "ablation_summary.json"
    summary_path.write_text(
        json.dumps({"profiles": summary_rows}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    md_path = out_dir / "ablation_summary.md"
    lines = [
        "# Retrieval ablation (measured)",
        "",
        "| Strategy | Hit Rate@5 | MRR | nDCG@5 | No-answer FP | P95 ms |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for row in summary_rows:
        lines.append(
            "| {profile} | {hit_rate_at_5:.3f} | {mrr:.3f} | {ndcg_at_5:.3f} | "
            "{no_answer_false_positive_rate:.3f} | {p95_retrieval_ms:.1f} |".format(**row)
        )
    lines.append("")
    lines.append(
        "_Generated by `scripts/run_ablation.py`. Do not hand-edit numbers._"
    )
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {summary_path} and {md_path}")
    return 0 if summary_rows else 1


if __name__ == "__main__":
    sys.exit(main())
